spring.datasource.url=jdbc:postgresql://trolley.proxy.rlwy.net:11378/railway
spring.datasource.username=postgres
spring.datasource.password=IVfknuzaAdgfpATeLnTQxtknXkWRIZph
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

resend.api.key=re_L6kyfeDD_5WKpPLtJCd5e7Fud3rKQTQQY

server.port=${PORT:8080}